
networks:

  proxy_net:
    external: true

services:
  wg_de:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg_de
    restart: unless-stopped
    user: "0:0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/wireguard:/etc/wireguard:rw
    env_file:
      - .env
    environment:
      - WG_HOST=${WG_HOST}   # your ip or domain or dyndns
      - PASSWORD_HASH=${PASSWORD_HASH}  # https://github.com/keenamateur/Homelab/blob/main/TOOLS/Wireguard_hash_generator
      - WG_DEFAULT_ADDRESS=10.10.50.x
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_DEFAULT_DNS=103.87.99.100, 103.86.99.100  # nordvpn dns
      - UI_TRAFFIC_STATS=true
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.tcp.routers.wg_de.entrypoints=wg_tcp"
    #   - "traefik.tcp.routers.wg_de.rule=HostSNI(`vpn_de.lan`)"
    #   - "traefik.tcp.services.wg_de.loadbalancer.server.port=51821"
    #   - "traefik.docker.network=proxy_net"     
    depends_on:
      - nvpn_de
    network_mode: service:nvpn_de

  nvpn_de:
    image: qmcgaw/gluetun
    container_name: nvpn_de
    user: "0:0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/gluetun:/gluetun
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=JUGOSLAVIA
      - COUNTRY_CODE=MoRDoR
      - TZ=Europe/Berlin
      - OPENVPN_USER= ${OPENVPN_USER}
      - OPENVPN_PASSWORD= ${OPENVPN_PASSWORD}
      - NET_LOCAL=192.168.2.0/24   # your lan subnet
      #- SERVER=BEST   # uncommenting this "disables" the country_code option in some cases
    ports:
      - '51850:51820/udp'
      - '51851:51821/tcp'
      - '3050:3000'
      - '3051:3001'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1   # maybe
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      proxy_net:
        ipv4_address: 172.30.10.50


