
networks:

  proxy_net:
    external: true

services:
  wg_de:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg_de
    restart: unless-stopped
    user: "0:0"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/wireguard:/etc/wireguard:rw
    env_file:
      - .env
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH= ${PASSWORD_HASH}
      - WG_DEFAULT_ADDRESS=10.10.50.x
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_DEFAULT_DNS=103.87.99.100, 103.86.99.100
      - UI_TRAFFIC_STATS=true
      #- WG_POST_UP=/srv/docker/system/vpnbridge/start.sh
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.tcp.routers.wg_de.entrypoints=wg_tcp"
    #   - "traefik.tcp.routers.wg_de.rule=HostSNI(`vpn_de.lan`)"
    #   - "traefik.tcp.services.wg_de.loadbalancer.server.port=51821"
    #   - "traefik.docker.network=proxy_net"     
    depends_on:
      - nvpn_de
    network_mode: service:nvpn_de

  nvpn_de:
    image: qmcgaw/gluetun
    container_name: nvpn_de
    user: "0:0"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/gluetun:/gluetun
#    command: ["/bin/bash", "/srv/docker/system/vpn_de/start_nvpn.sh"]
    env_file:
      - .env
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Germany
      - COUNTRY_CODE=DE
      - TZ=Europe/Berlin
      #- WIREGUARD_ADDRESSES=10.5.0.2/32
      #- WIREGUARD_PRIVATE_KEY=$${PRIVATE_KEY}
      - OPENVPN_USER= ${OPENVPN_USER}
      - OPENVPN_PASSWORD= ${OPENVPN_PASSWORD}
      - NET_LOCAL=192.168.2.0/24
      - SERVER=BEST
    ports:
      - '51850:51820/udp'
      - '51851:51821/tcp'
      - '3050:3000'
      - '3051:3001'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1   # maybe
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      proxy_net:
        ipv4_address: 172.30.10.50


